### ISSUE TITLE
How to use confirmed rule?

### ISSUE THREAD

**Issue by kelmadhoun** [gokulakannant/react-form-input-validation#20]
Hi,

I've been trying to use the rule `confirmed` for a long time but i couldn't do it, please explain how to use it, and why is it not like the rule `'different:attribute'`?
This is my code:

```
this.form.useRules({
        email: "required|email",
        password: "required|custom_password_rule",
        password_confirmation: "confirmed",
});
```

Now how to link password with password_confirmation, shall i do it in the html code? how?

Thanks!

**Comment by gokulakannant** [comment]
We can validate confirm password in two ways,

1) Using `confirmed` validation rule

```
this.form.useRules({
        email: "required|email",
        password: "required|custom_password_rule|confirmed",
        password_confirmation: "requried",
});
```

2) Using `same` validation rule,

```
this.form.useRules({
        email: "required|email",
        password: "required|custom_password_rule",
        password_confirmation: "requried|same:password",
});
```
