### ISSUE TITLE
Form validation with React Functional Component and useState Hooks

### ISSUE THREAD

**Issue by Olawumi-Olusegun** [gokulakannant/react-form-input-validation#41]
Hi, how can I possibly use the react-form-validation API in a React Functional Component and useState Hooks? Thanks.

**Comment by gokulakannant** [comment]
Hi, I know it's too late. But now our package supports functional components as well. 

Reference: [useFormInputValidation](https://gokulakannant.github.io/react-form-input-validation/v2.1.0/functions/Hooks.useFormInputValidation.html)
